language: python

python:
  - "2.7"

os:
  - osx
  - linux

notifications:
    email: never

before_install:
  - pip install -q pytest
  - pip install -q coveralls

install:
  - python setup.py install

script:
  - coverage run --source documenter setup.py test
  - coverage report

after_success:
  - coveralls

